### ISSUE TITLE
关于提示Demo period has expired过期问题

### ISSUE THREAD

**Issue by oilrich25** [BlackHatRCE/hop-osx#1]
在intel版本当中，会出现Demo period has expired过期的问题问题发生。而arm64版本则不会出现，请修复intel版本

<img width="182" alt="11" src="https://github.com/BlackHatRCE/hop-osx/assets/152663740/a2d80450-5668-4565-a41d-9d75f7bc8678">

**Comment by BlackHatRCE** [comment]
Updated to 5.15.6 and fixed the bug.
